@startuml
start
: Determine if the node is a parent or a child;

if (Is Parent Node?) then (yes)
    :Find and connect to children nodes;
    :Start Packet Capture;
    partition "Network Communication" {
        :Continuous Network Monitoring;
        :Handle Network Errors;
        :Decide communication protocol based on noise;
    }
    partition "API Communication" {
        :Make Secure API Calls to control lights;
        :Handle API Response;
        --> "Determine where lights are";
    }
    :Determine where lights are;
    :Generate and maintain list of candidate user devices;
    :Perform triangulation;
    :Calculate distances;
    --> "Start Packet Capture"; ' Loop back to continuously adjust and monitor
else (no)
    :Start Packet Capture;
    partition "Network Communication" {
        :Continuous Network Monitoring;
        :Handle Network Errors;
        :Decide communication protocol based on noise;
        :Communicate distance data to parent;
        :Configure based on parent commands;
        --> "Start Packet Capture"; ' Loop back to monitor network and adjust configuration
    }
endif

stop
@enduml
